baseURL = 'https://personal-blog-site-steel.vercel.app/'
languageCode = 'en-us'
title = 'Blog @ sntx.dev'
theme ='tophat'
paginate = 5

[params]
    
  subtitle = 'https://sntx.dev/'
  description = "sntx.dev's blog!"
  author = "Miles Hilliard"

  main = "post"
  featured = true
  
  # You can customize the visibility of some elements like date, reading time, words counter and tags inside article by setting true or false
  show_date_on_article = true
  show_reading_time_on_article = true
  show_words_count_on_article = true
  show_tags_on_article = true  

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "https://sntx.dev/"

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "https://sntx.dev/"
  
  [[menu.social]]
    identifier = "discord"
    name = "Discord"
    url = "https://discord.com/users/7896867932712366090" 

  [[menu.social]]
    identifier = "github"
    name = "Github"
    url = "https://github.com/syntaxerror019"

  [[menu.social]]
    identifier = "ko-fi"
    name = "Support"
    url = "https://ko-fi.com/sntxdev"

